on:
  workflow_dispatch:
    inputs:
      text:
        type: string
        default: 'text'
jobs:
  repository-call: # This will run first 
    uses: TaYaKi71751/WorkflowTest/.github/workflows/PrintCall.yml@main # specify version(branch)
    with:
      text: ${{ github.event.inputs.text }}
  local-call: # This will run when success [repository-call]
    needs: [repository-call]
    uses: ./.github/workflows/PrintCall.yml # cannot specify version(branch) when calling local workflows
    with:
      text: ${{ github.event.inputs.text }}
